FROM python:3.9

WORKDIR /app

RUN apt-get update --yes && \
    apt-get install git apt-utils -qq -y && \
    apt-get upgrade --yes

COPY requirements.txt /app

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# TODO: install nextflow
