channels:
  - conda-forge
  - anaconda
  - bioconda
dependencies:
  - black=22.1.*
  - flake8=3.8.*
  - ipykernel=6.9.*
  - ipython=8.0.*
  - jupyterlab=3.2.*
  - matplotlib=3.5.*
  - pandas=1.4.*
  - pylint=2.9.*
  - pytest=6.2.*
  - scikit-learn=1.0.*
  - umap-learn=0.5.*
